### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by bear-frog** [sosotable/ssossotest#4]
## TODO 
    회의 일시: 2023/03/04(토) 14:00 서울역 카페 파스쿠치

### 1. 소소테스트 서버 배포
- server-info ssossotest 참조(key, IP address)

### 2. 소소테스트 평균, 취향 테스트 완성
- 회의 날짜까지 완성

### 3. 커밋
- 금 / 월 이틀 깃허브에 커밋로그 찍으세요

### 기타
- 작업 시작, 완료 여부 깃허브 TODO 이슈에 comment로 넣으세요
- 작업 내용은 본인 풀리퀘스트에 커밋으로 넣으세요
    - 회의 날짜에 병합

**Comment by bear-frog** [comment]
### PROGRESS: SSR porting
---

서버사이드 편리화를 위하여 프로젝트의 CSR > SSR 포팅을 진행합니다
서버리스 작업으로 퀘이사를 통해 백엔드 작업을 처리하도록 하는 것이 목적입니다
예상 작업 기간은 2023-02-25 > 2023-02-26 입니다

**Comment by hyunjo01** [comment]
### FEAT: average page, average result page
---
- average 문제 page vue로 코팅
- average 결과 page 구현

**Comment by Ujin28** [comment]
FEAT: TastesResultPage.vue
--
결과값 받아서 보여주기


REFACTOR: TastesPage.vue
---
